Implement entropy measure of password strength and configuration
kevinwojo/hubzero-cms pull request #1
Opened 2017-05-30 20:25 UTC by wei170

2017-06-14 17:57 UTC, kevinwojo commented on core/composer.json
> +		"bjeavons/zxcvbn-php": "^0.3"
Does the CMS need this library too? Just the framework?

2017-06-14 17:57 UTC, kevinwojo commented on core/components/com_members/admin/controllers/members.php
> +		if ($filters['status'])
What is this block supposed to do? It appears to be commented out.

2017-06-14 18:40 UTC, wei170 commented on core/components/com_members/admin/controllers/members.php
> +		if ($filters['status'])
I was trying to filter the user log records by its status. Still working on that

2017-06-14 18:51 UTC, wei170 commented on core/components/com_members/admin/controllers/members.php
> +		if ($filters['status'])
Since I just realized that if the key to relate jos_users_log_auth and jos_users is 'username' instead of 'user_id'

2017-06-16 19:08 UTC, kevinwojo requested changes

2017-06-16 19:08 UTC, kevinwojo commented on .gitignore
> +
remove these guys

2017-06-16 19:08 UTC, kevinwojo commented on core/components/com_members/admin/controllers/members.php
> +			$auth->set('status', 'released');
add a new row instead of setting value

2017-06-16 19:08 UTC, kevinwojo commented on core/components/com_members/admin/language/en-GB/en-GB.com_members.members.ini
> +COM_MEMBERS_FILTER_STATUS="- Latest Log Status -"
delete 45 - 47

2017-06-16 19:08 UTC, kevinwojo commented on core/components/com_members/admin/views/members/tmpl/display.php
> +
Remove space

2017-06-16 19:08 UTC, kevinwojo commented on core/components/com_members/admin/views/members/tmpl/display.php
> +					<option value="*"><?php echo Lang::txt('COM_MEMBERS_OPTION_FILTER_DATE');?></option>
typo

2020-01-07 13:55 UTC, closed without merging